using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using Oracle.ManagedDataAccess.Client;

namespace StudentManagementSystem.Forms
{
    [System.ComponentModel.DesignerCategory("Form")]
    [System.ComponentModel.DesignTimeVisible(true)]
    public partial class DangKyHocPhanForm : Form
    {
        private string _maSV = "";
        private string _currentUser = "";
        private string _connStr = "User Id=ADMIN_MASTER;Password=123;Data Source=localhost:1521/orcl21pdb1;";
        

        public DangKyHocPhanForm()
        {
            // Avoid accessing runtime-only services in the constructor so the
            // Visual Studio Designer can instantiate this form at design-time.
            InitializeComponent();
        }

        

        private void Form_Load(object? sender, EventArgs e)
        {
            // Set current user only at runtime (not at design-time). Designer
            // instantiates the form but cannot rely on DAL or DB connections.
            try
            {
                if (System.ComponentModel.LicenseManager.UsageMode != System.ComponentModel.LicenseUsageMode.Designtime)
                {
                    _currentUser = DAL.OracleConnection.Instance.CurrentUser ?? "";
                }
            }
            catch
            {
                _currentUser = "";
            }

            // Ensure columns are not auto-generated by the DataGridView
            // and create our fixed columns before binding data.
            try
            {
                dgvLeft.AutoGenerateColumns = false;
                dgvRight.AutoGenerateColumns = false;
                SetupGridColumns(dgvLeft);
                SetupGridColumns(dgvRight);
            }
            catch { }

            LoadMaSV();
            LoadAll();
        }

        private void SetupGridColumns(DataGridView dgv)
        {
            dgv.Columns.Clear();

            var cMA = new DataGridViewTextBoxColumn();
            cMA.Name = "MAHP";
            cMA.HeaderText = "MAHP";
            cMA.DataPropertyName = "MAHP";
            // Fix MAHP to a hard pixel width
            cMA.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            cMA.Width = 100;

            var cTEN = new DataGridViewTextBoxColumn();
            cTEN.Name = "TENHP";
            cTEN.HeaderText = "TENHP";
            cTEN.DataPropertyName = "TENHP";
            // Fix TENHP to a hard pixel width (wide)
            cTEN.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            cTEN.Width = 408; 

            var cHK = new DataGridViewTextBoxColumn();
            cHK.Name = "HOCKY";
            cHK.HeaderText = "HOCKY";
            cHK.DataPropertyName = "HOCKY";
            // Fix HOCKY to a small fixed width
            cHK.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            cHK.Width = 100; 

            var cNH = new DataGridViewTextBoxColumn();
            cNH.Name = "NAMHOC";
            cNH.HeaderText = "NAMHOC";
            cNH.DataPropertyName = "NAMHOC";
            // Fix NAMHOC to a moderate fixed width
            cNH.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            cNH.Width = 100;

            dgv.Columns.AddRange(new DataGridViewColumn[] { cMA, cTEN, cHK, cNH });
        }

        private void LoadMaSV()
        {
            try
            {
                using (var conn = new OracleConnection(_connStr))
                {
                    conn.Open();
                    using (var cmd = new OracleCommand("SELECT MASV FROM ADMIN_MASTER.SINHVIEN WHERE UPPER(ORACLEUSERNAME) = UPPER(:u)", conn))
                    {
                        cmd.Parameters.Add(":u", _currentUser);
                        var result = cmd.ExecuteScalar();
                        _maSV = result?.ToString() ?? "";
                        lblInfo.Text = "Sinh viên: " + _currentUser.ToUpper() + " | Mã SV: " + _maSV;
                    }
                }
            }
            catch (Exception ex)
            {
                lblInfo.Text = "Lỗi: " + ex.Message;
            }
        }

        private void LoadAll()
        {
            LoadHocPhanChuaDK();
            LoadHocPhanDaDK();
        }

        private void LoadHocPhanChuaDK()
        {
            try
            {
                using (var conn = new OracleConnection(_connStr))
                {
                    conn.Open();
                    string sql = "SELECT HP.MAHP, HP.TENHP, HP.HOCKY, HP.NAMHOC " +
                                 "FROM ADMIN_MASTER.HOCPHAN HP " +
                                 "WHERE HP.TRANGTHAI = 1 " +
                                 "AND NOT EXISTS (SELECT 1 FROM ADMIN_MASTER.DIEM D WHERE D.MAHP = HP.MAHP AND D.MASV = :masv) " +
                                 "ORDER BY HP.NAMHOC DESC, HP.HOCKY DESC";

                    using (var cmd = new OracleCommand(sql, conn))
                    {
                        cmd.Parameters.Add(":masv", _maSV);
                        var dt = new DataTable();
                        using (var adapter = new OracleDataAdapter(cmd))
                        {
                            adapter.Fill(dt);
                        }
                        dgvLeft.DataSource = dt;
                        // Print column widths for debugging/verification
                        PrintColumnWidths(dgvLeft, "Left");
                        // columns are created in SetupGridColumns; data binds by DataPropertyName
                        lblLeft.Text = "HỌC PHẦN CÓ THỂ ĐĂNG KÝ: " + dt.Rows.Count;
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi load học phần: " + ex.Message);
            }
        }

        private void LoadHocPhanDaDK()
        {
            try
            {
                using (var conn = new OracleConnection(_connStr))
                {
                    conn.Open();
                    string sql = "SELECT D.MAHP, HP.TENHP, HP.HOCKY, HP.NAMHOC " +
                                 "FROM ADMIN_MASTER.DIEM D " +
                                 "INNER JOIN ADMIN_MASTER.HOCPHAN HP ON D.MAHP = HP.MAHP " +
                                 "WHERE D.MASV = :masv " +
                                 "ORDER BY D.NGAYNHAP DESC";

                    using (var cmd = new OracleCommand(sql, conn))
                    {
                        cmd.Parameters.Add(":masv", _maSV);
                        var dt = new DataTable();
                        using (var adapter = new OracleDataAdapter(cmd))
                        {
                            adapter.Fill(dt);
                        }
                        dgvRight.DataSource = dt;
                        // Print column widths for debugging/verification
                        PrintColumnWidths(dgvRight, "Right");
                        // columns created in SetupGridColumns; data binds by DataPropertyName
                        lblRight.Text = "HỌC PHẦN ĐÃ ĐĂNG KÝ: " + dt.Rows.Count;
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi load đã đăng ký: " + ex.Message);
            }
        }

        private void BtnDangKy_Click(object? sender, EventArgs e)
        {
            if (dgvLeft.CurrentRow == null || dgvLeft.RowCount == 0)
            {
                MessageBox.Show("Vui lòng chọn học phần!", "Thông báo");
                return;
            }

            string maHP = dgvLeft.CurrentRow.Cells["MAHP"].Value?.ToString() ?? "";
            string tenHP = dgvLeft.CurrentRow.Cells["TENHP"].Value?.ToString() ?? "";

            if (string.IsNullOrEmpty(maHP) || string.IsNullOrEmpty(_maSV))
            {
                MessageBox.Show("Dữ liệu không hợp lệ!", "Lỗi");
                return;
            }

            var result = MessageBox.Show(
                "Đăng ký học phần:\n\nMã HP: " + maHP + "\nTên: " + tenHP,
                "Xác nhận đăng ký",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question);

            if (result == DialogResult.Yes)
            {
                try
                {
                    using (var conn = new OracleConnection(_connStr))
                    {
                        conn.Open();

                        string maDiem = "DK_" + _maSV + "_" + maHP + "_" + DateTime.Now.ToString("yyyyMMddHHmmss");

                        using (var cmd = new OracleCommand(
                            "INSERT INTO ADMIN_MASTER.DIEM (MADIEM, MASV, MAHP, NGAYNHAP, NGUOINHAP) VALUES (:madiem, :masv, :mahp, SYSDATE, :nguoi)", conn))
                        {
                            cmd.Parameters.Add(":madiem", maDiem);
                            cmd.Parameters.Add(":masv", _maSV);
                            cmd.Parameters.Add(":mahp", maHP);
                            cmd.Parameters.Add(":nguoi", _currentUser);
                            cmd.ExecuteNonQuery();
                        }

                        // COMMIT
                        using (var commitCmd = new OracleCommand("COMMIT", conn))
                        {
                            commitCmd.ExecuteNonQuery();
                        }

                        MessageBox.Show("Đăng ký thành công!\n\n" + tenHP, "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        LoadAll();
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Lỗi đăng ký: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        private void BtnHuy_Click(object? sender, EventArgs e)
        {
            if (dgvRight.CurrentRow == null || dgvRight.RowCount == 0)
            {
                MessageBox.Show("Vui lòng chọn học phần đã đăng ký!", "Thông báo");
                return;
            }

            string maHP = dgvRight.CurrentRow.Cells["MAHP"].Value?.ToString() ?? "";
            object? diemGK = null;
            try
            {
                // Safe check: DataGridView may be bound to a DataTable without the DIEMGIUAKY column,
                // or the column may not be present in our manually created columns. Prefer reading
                // from the underlying DataRowView when available, and fall back to checking the
                // named cell only if the column exists.
                if (dgvRight.CurrentRow?.DataBoundItem is DataRowView drv)
                {
                    if (drv.Row.Table.Columns.Contains("DIEMGIUAKY"))
                        diemGK = drv["DIEMGIUAKY"];
                }
                else if (dgvRight.Columns.Contains("DIEMGIUAKY"))
                {
                    diemGK = dgvRight.CurrentRow.Cells["DIEMGIUAKY"].Value;
                }
            }
            catch { diemGK = null; }

            if (diemGK != null && diemGK != DBNull.Value)
            {
                MessageBox.Show("Không thể hủy - đã có điểm!", "Thông báo");
                return;
            }

            var result = MessageBox.Show(
                "Hủy đăng ký học phần: " + maHP + "?",
                "Xác nhận hủy",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning);

            if (result == DialogResult.Yes)
            {
                try
                {
                    using (var conn = new OracleConnection(_connStr))
                    {
                        conn.Open();

                        using (var cmd = new OracleCommand(
                            "DELETE FROM ADMIN_MASTER.DIEM WHERE MASV = :masv AND MAHP = :mahp", conn))
                        {
                            cmd.Parameters.Add(":masv", _maSV);
                            cmd.Parameters.Add(":mahp", maHP);
                            cmd.ExecuteNonQuery();
                        }

                        using (var commitCmd = new OracleCommand("COMMIT", conn))
                        {
                            commitCmd.ExecuteNonQuery();
                        }

                        MessageBox.Show("Đã hủy đăng ký!", "Thành công");
                        LoadAll();
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Lỗi: " + ex.Message, "Lỗi");
                }
            }
        }

        private void BtnRefresh_Click(object? sender, EventArgs e)
        {
            LoadAll();
            MessageBox.Show("Đã làm mới dữ liệu!", "Thông báo");
        }

        private void PrintColumnWidths(DataGridView dgv, string gridName)
        {
            try
            {
                if (dgv.Columns == null || dgv.Columns.Count == 0) return;
                int total = dgv.ClientSize.Width > 0 ? dgv.ClientSize.Width : dgv.Width;
                Console.WriteLine($"[{gridName}] DataGridView ClientWidth = {total}");
                foreach (DataGridViewColumn col in dgv.Columns)
                {
                    double pct = total > 0 ? (col.Width * 100.0 / total) : 0;
                    Console.WriteLine($"[{gridName}] Col={col.Name}, Width={col.Width}, Pct={pct:F1}%, FillWeight={col.FillWeight}");
                }
            }
            catch { }
        }
    }
}
